spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=USER;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:schema-dev.sql
      data-locations: classpath:data-dev.sql