server:
  port: 9000

spring:
  web:
    resources:
      static-locations: classpath:/static/angular-frontend/browser
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
