server:
  port: 80

spring:
  web:
    resources:
#      static-locations: classpath:/static/angular-frontend/browser
      static-locations: classpath:/static
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

