spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/langapp
    username: root
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true;
#  sql:
#    init:
#      mode: always
  sql:
    init:
      schema-locations: classpath:schema-dev.sql
      data-locations: classpath:data-dev.sql
